server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        namespace: dev
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
      - id: user
        uri: lb://user-service
        predicates:
          - Path=/user/**
